services:
  crawler1:
    build:
      context: ..
      dockerfile: ./docker/crawler.Dockerfile
    environment:
      - ARCHIVIST_NETWORK=testnet
      - ARCHIVIST_VERSION=latest
      - CRAWLER_LOGLEVEL=TRACE
      # - CRAWLER_PUBLICIP= Set to override CURL to ip.archivist.storage
      - CRAWLER_METRICSADDRESS=0.0.0.0
      - CRAWLER_METRICSPORT=8008
      - CRAWLER_DATADIR=crawler_data
      - CRAWLER_DISCPORT=8090
      - CRAWLER_BOOTNODES=testnet_sprs
      - CRAWLER_STEPDELAY=3000
      - CRAWLER_REVISITDELAY=1440
    ports:
      - 8008:8008/tcp # Metrics
      - 8090:8090/udp # DHT discovery
    volumes:
      - ./crawler_data:/crawler_data:z
